# Generated by Django 4.2.1 on 2023-06-02 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projection',
            name='film_capacity',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='film_duration',
        ),
        migrations.RemoveField(
            model_name='projection',
            name='film_name',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='film',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='projection',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projection',
            name='imeFilma',
            field=models.CharField(default='default_value', max_length=40),
        ),
        migrations.AddField(
            model_name='projection',
            name='kapacitetDvorane',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projection',
            name='vrijemeFilma',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='brojSjedala',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='idKorisnik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='idProjekcija',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinemaApp.projection'),
        ),
        migrations.DeleteModel(
            name='UserProfileInfo',
        ),
    ]
