# Generated by Django 4.2.1 on 2023-06-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemaApp', '0002_remove_projection_film_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projection',
            name='imeFilma',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
