# Generated by Django 4.2.2 on 2023-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.CharField(choices=[('admin', 'Admin'), ('profesor', 'Profesor'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
