# Generated by Django 4.2.2 on 2023-06-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_user_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('upisan', 'Upisan'), ('potpis izgubljen', 'Potpis izgubljen'), ('polozen', 'Polozen')], default='upisan', max_length=20),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='izborni',
            field=models.CharField(choices=[('da', 'Da'), ('ne', 'Ne')], default='da', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('redovni', 'Redovni'), ('izvanredni', 'Izvanredni')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='MandatoryStatus',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='StudentStatus',
        ),
        migrations.DeleteModel(
            name='SubjectStatus',
        ),
    ]
