# Generated by Django 4.2.2 on 2023-06-25 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_remove_user_role_alter_enrollment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('profesor', 'Profesor'), ('student', 'Student')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='userrole',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='nositelj',
            field=models.ForeignKey(limit_choices_to={'userrole': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='managementApp.role'),
        ),
    ]
