# Generated by Django 4.2.2 on 2023-06-25 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_role_remove_user_userrole_alter_subjects_nositelj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='nositelj',
            field=models.ForeignKey(limit_choices_to={'userrole__role': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
